### ISSUE TITLE
Suggestion: use JSON::MaybeXS

### ISSUE THREAD

**Issue by kentfredric** [demianriccardi/HackaMol-Roles-SerialRole#3]
JSON::MaybeXS might be a better option than consuming JSON::XS directly.

Mostly because JMXS auto-proxies to all of: 
- Cpanel::JSON::XS
- JSON::XS
- JSON:PP

Based on availability, slightly increasing the range of targets you can support.

I'd also suggest not loading all the encoders only to use one of them, and possibly avoiding a system of hard-coded conditionals working out how to encode/decode. ( Also, maybe steal parts from / maybe try using https://metacpan.org/release/Data-Serializer  )

**Comment by demianriccardi** [comment]
Thanks for the suggestions, @kentfredric!
